// data.js
export const rows = [
  {
    id: 1,
    name: "Cloud Storage Basic",
    serviceName: "Basic Storage Plan",
    supplierName: "Cloud Services Inc.",
    client: "Tech Solutions LLC",
    startDate: "2022-01-01",
    expiryDate: "2023-01-01",
    status: "Not expired",
  },
  {
    id: 2,
    name: "Cloud Hosting Pro",
    serviceName: "Pro Hosting Plan",
    supplierName: "Cloud Services Inc.",
    client: "Online Retailers Ltd.",
    startDate: "2022-03-15",
    expiryDate: "2023-03-15",
    status: "Expired",
  },
  {
    id: 3,
    name: "Cloud Database Enterprise",
    serviceName: "Enterprise Database Plan",
    supplierName: "Data Solutions Co.",
    client: "Financial Services Corp.",
    startDate: "2022-02-10",
    expiryDate: "2022-12-10",
    status: "Not expired",
  },
  {
    id: 4,
    name: "Cloud Backup Plus",
    serviceName: "Premium Backup Plan",
    supplierName: "Cloud Services Inc.",
    client: "Healthcare Systems Ltd.",
    startDate: "2022-05-20",
    expiryDate: "2023-05-20",
    status: "Not expired",
  },
  {
    id: 5,
    name: "Cloud Development Suite",
    serviceName: "Developer Tools Suite",
    supplierName: "DevTech Solutions",
    client: "Software Innovations Inc.",
    startDate: "2022-04-01",
    expiryDate: "2023-04-01",
    status: "Expired",
  },
  {
    id: 6,
    name: "Cloud Computing Essentials",
    serviceName: "Essential Cloud Package",
    supplierName: "Cloud Solutions Ltd.",
    client: "Global Enterprises Inc.",
    startDate: "2022-06-15",
    expiryDate: "2023-06-15",
    status: "Not expired",
  },
  {
    id: 7,
    name: "Cloud Security Suite",
    serviceName: "Security Management Plan",
    supplierName: "SecureCloud Inc.",
    client: "Financial Holdings Group",
    startDate: "2022-07-10",
    expiryDate: "2023-07-10",
    status: "Not expired",
  },
  {
    id: 8,
    name: "Cloud Analytics Platform",
    serviceName: "Advanced Analytics Plan",
    supplierName: "Data Insights Corp.",
    client: "Tech Innovations LLC",
    startDate: "2022-08-20",
    expiryDate: "2023-08-20",
    status: "Expired",
  },
  {
    id: 9,
    name: "Cloud Backup Pro",
    serviceName: "Professional Backup Service",
    supplierName: "Backup Solutions Ltd.",
    client: "Online Retailers Inc.",
    startDate: "2022-09-05",
    expiryDate: "2023-09-05",
    status: "Expired",
  },
  {
    id: 10,
    name: "Cloud AI Services",
    serviceName: "AI Integration Package",
    supplierName: "AI Technologies Inc.",
    client: "Tech Solutions Ltd.",
    startDate: "2022-10-01",
    expiryDate: "2023-10-01",
    status: "Not expired",
  },
];
